{
 "title": "Eye",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "box", "label": "box", "query": { "query": "label_values(box)" } }
  ]
 },
 "panels": [
  {
   "title": "Busiest core",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eye_cpu_utilization_busiest{box=~\"$box\"}",
     "legendFormat": "{{box}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eye_cpu_utilization_all{box=~\"$box\"}",
     "legendFormat": "{{box}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eye_cpu_utilization_all{box=~\"$box\"}",
     "legendFormat": "{{box}} [all]"
    },
    {
     "expr": "eye_cpu_utilization_busiest{box=~\"$box\"}",
     "legendFormat": "{{box}} [busiest]"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eye_memory_utilization{box=~\"$box\"}",
     "legendFormat": "{{box}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eye_memory_utilization{box=~\"$box\"}",
     "legendFormat": "{{box}}"
    }
   ]
  },
  {
   "title": "Storage utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eye_mounts_utilization{box=~\"$box\"}",
     "legendFormat": "{{box}} [{{mountpoint}}]"
    }
   ]
  },
  {
   "title": "Storage utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eye_mounts_utilization{box=~\"$box\"}",
     "legendFormat": "{{box}} [{{mountpoint}}]"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(eye_network_received_bytes_total{box=~\"$box\"}[1m]) * 8",
     "legendFormat": "{{box}} [{{iface}}][in]"
    },
    {
     "expr": "rate(eye_network_transmitted_bytes_total{box=~\"$box\"}[1m]) * 8",
     "legendFormat": "{{box}} [{{iface}}][out]"
    }
   ]
  },
  {
   "title": "IO operations in progress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eye_disks_in_progress{box=~\"$box\"}",
     "legendFormat": "{{box}} [{{dev}}]"
    }
   ]
  }
 ]
}