apiVersion: 1
datasources:
{{ range . }}
- name: {{ .Name }}
  type: {{ .Type }}
  access: proxy
  orgId: 1
  url: {{ .URL }}
  version: 1
  editable: false
  jsonData:
    timeInterval: 5s
{{ end }}
