auth_enabled: false

server:
  http_listen_port: {{ .HTTPPort }}
  log_format: json
  log_level: error

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /app

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /app/chunks
  tsdb_shipper:
    active_index_directory: /app/tsdb/index
    cache_location: /app/tsdb/index_cache

analytics:
  reporting_enabled: false

limits_config:
  retention_period: 48h

compactor:
  working_directory: /app/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem
